name: Publish to Maven Central
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Gradle Permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Run Tests
        run: ./gradlew test

  push-to-maven-central:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Gradle Permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Set tags env
        run: echo "RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: Gradle publish to Maven Central
        run: ./gradlew publishPlugins -Pversion=${{ env.RELEASE_VERSION }}  -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
