name: Publish to Maven Central
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Gradle Permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Run Tests
        run: ./gradlew test

  push-to-maven-central:
    runs-on: ubuntu-latest
    needs: test
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_PGP_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_PGP_KEY_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Gradle Permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Set tags env
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/:1}" >> $GITHUB_ENV

      - name: Gradle publish to Maven Central
        run: ./gradlew -Pversion=${{ env.RELEASE_VERSION }} publishMavenJavaPublicationToMavenCentralRepository -i